name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  increase-build-number:
    default: "true"
    required: false
    description: "Set this to true to increase the version number by one (true|false)"
runs:
  using: "node16"
  main: "dist/index.js"
